# Generated by Django 5.1.2 on 2024-10-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollments',
            name='status',
            field=models.CharField(choices=[('IN_PROCESS', 'IN PROCESS'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='IN PROCESS'),
        ),
    ]
