# Generated by Django 5.1.2 on 2024-10-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_courses_introductor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
