# Generated by Django 5.1.2 on 2024-10-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_courses_introductor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='verify_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
