# Generated by Django 5.1.4 on 2024-12-10 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_users_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='lession_id',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='lession_id',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='introductor_id',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='process',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='process',
            name='progress_percentage',
        ),
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='last_accessed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('IN_PROCESS', 'IN PROCESS'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='IN PROCESS'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.courses'),
        ),
        migrations.AlterField(
            model_name='process',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('video_url', models.URLField(blank=True, null=True)),
                ('img_url', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='app.courses')),
            ],
        ),
        migrations.AddField(
            model_name='assignments',
            name='lesson_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lessons'),
        ),
        migrations.AddField(
            model_name='courses',
            name='lesson_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lessons'),
        ),
        migrations.AddField(
            model_name='process',
            name='lesson_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lessons'),
        ),
        migrations.DeleteModel(
            name='Lessions',
        ),
    ]
