# Generated by Django 5.1.4 on 2024-12-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_process_lession_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('USER', 'USER'), ('ADMIN', 'ADMIN'), ('LECTURER', 'LECTURER')], default='USER', max_length=20),
        ),
    ]
